name: 'gold_marts'
version: '1.0.0'
config-version: 2

profile: 'gold_marts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  gold_marts:
    +materialized: table
    +file_format: delta
    marts:
      +schema: gold_retail
      +tags: ["gold", "retail"]

vars:
  start_date: '2020-01-01'
